internal/collector/collector.go
signum signal for SIGJSON sends to Keepalived on not using useJSON flag so if Keepalived doesn't support SIGJSON, Keepalived Exporter will be panic!
=> Fix bug on calculating SIGJSON on not using useJSON flag

go.sum, internal/collector/collector.go, internal/collector/parser.go, internal/collector/signal.go
In some times exporter will stuck because of high response time of signals and prometheus will stuck too.
Now we have set a timeout of 1sec for getting response from Keepalived and if there were no response from Keepalived we will proceed with previous data if it has dumped and we will wait for Keepalived to dump stats in another goroutine.
=> Fix bug on stuck for Keepalived signal response

Makefile
=> Update golangci-lint to 1.24.0

internal/collector/collector.go
If there were a failure on pinging VIP the ping packet loss metric will become 100% to warn something isn't working!
=> Set ping packet loss to 100% on failure

README.md, cmd/keepalived-exporter/main.go, internal/collector/collector.go, internal/collector/parser.go, internal/collector/signal.go
This may cause Keepalived Exporter to be stuck on not replying before another prometheus request.
The default value for ping timeout was 100000sec! It is now configurable via ping.timeout arg.
Related to #8 but not fixing!
=> Make ping timeout configurable

internal/collector/collector.go
There was a typo in garp delay exported metric
=> Fix typo in garp delay exported metric

internal/collector/collector.go
Sometimes there is a output for a script that can help in error logs
=> Add check script output to error logging

grafana/dashboards/keepalived-exporter.json
According to d6258d5 (Add _total postfix for counter metrics,
2020-05-08) and 48caff1 (fix: Change names to prometheus standards,
2020-06-13)
=> Fix Grafana dashboard metrics

internal/collector/parser.go
Keepalived data file can contain following info
```
VRRP Instance = server.domain.com
VRRP Version = 2
State = MASTER
...
Interface = ens33
VRRP interface tracking disabled
```
The last citated line does not look like `PROPERTY = VALUE`, so the `parseVRRPData`
function stops iterating properties and so does not gather some info: `vrid`
and `Virtual IP` info, for example.
Let's just skip such lines.
=> Fixed bug parsing text data | E.g. no VRID set, no Virtual IP info (keepalived_vrrp_state metric)

internal/collector/parser.go, internal/collector/parser_test.go
There maybe two `Virtual IP` format in in keepalived.data that in both we just need index 0 and 2 for ip and interface and we could ignore others.
=> fix: parse Virtual IP more than 5 chars

Makefile, cmd/keepalived-exporter/main.go
Inject version, commit, and buildTime metadata when building.
Closes #46.
=> build: Add version flag to show metadata info

internal/types/host/keepalived_host_collector_host.go, internal/types/host/utils.go, internal/types/host/utils_test.go
Because of \n in output, this could be done with json.Unmarshal func
Fixes: #59
=> fix: parse signum with json.Unmarshal in host mode

README.md
GitHub Packages Docker Registry (aka docker.pkg.github.com) is deprecated and will sunset early next year.
=> docs: switch to GitHub container registry

.github/workflows/release.yml
This PR adds support of building binary packages + their checksum on a release event and attaches them to the release page based on the Github actions. For example, see https://github.com/meysampg/keepalived-exporter/releases/tag/v1.2.2 (The version number is just for testing purposes).
- Add `.github/workflows/release.yml` file
- Add `-s` flag to `ldflags` to drop symbol table for reduce binary size
- Add `-w` flag to `ldflags` to disable DWARF generation for reduce binary size
=> build: add support of automatic binary building on release

internal/collector/parser.go, internal/collector/parser_test.go, test_files/v2.2.7/keepalived.data
might fix https://github.com/mehdy/keepalived-exporter/issues/84
I noticed this on a recent keepalived 2.2.7 version where no `keepalived_vrrp_state` was being reported.
looks like the format has been updated to reflect a count along with `Virtual IP` string, see https://github.com/acassen/keepalived/commit/8e0371a1598e4669213a73d40c20e1e378a5b7e3#diff-0223680d17d787f6b86e04dc2f561503d4e8331d7e5f494ec98fb397733ea285L736
please review.
=> fix: adapt parsing logic for keepalived v2.2.7

internal/collector/collector.go, internal/collector/collector_test.go, internal/collector/parser.go, internal/collector/parser_test.go
As the vrrp state would change from time to time, having it as a label will lead to introducing new metrics which isn't a good practice. It will also make duplicated metrics in grafana dashboard view which is unnecessary.
Signed-off-by: Seena Fallah <seenafallah@gmail.com>
=> fix: drop state label from metrics

internal/types/container/keepalived_container_collector_host.go, internal/types/host/keepalived_host_collector_host.go, internal/types/utils/files.go, internal/types/utils/files_test.go
In the default wait time of 10ms, if the keepalive state has not been generated, setting the max wait time to 100ms in the PROD ENV has been met the requirements.
Here, the max waiting time for the state file is set to 2s, and the waiting time for each retry will gradually increase. If the file is not generated in the first 10ms, then wait for 50ms, 100ms, 200ms, 400ms, 800ms, and 1s sequentially. If it is not completed within the max total waiting time of 2s, the service is considered to have failed.
#85
Closes #75
=> feat: open the keepalived stats file with retry support

internal/collector/collector.go
With old keepalived version, the `Virtual IP` key does not exist so the `keepalived_vrrp_state` is missing.
This PR add the possibility to have the vrrp_state metrics even when VIPs are not defined.
Otherwise no breaking changes.
=> fix: add vrrp_state metric even when VIPs are not defined

.golangci-lint.yml, Makefile, go.mod, go.sum
To address the issue: https://github.com/moby/moby/issues/45935
=> chore: update docker to v24.0.5

.goreleaser.yaml
Thanks for writing this exporter!
- makes the goreleaser config compatible with latest release
- creates artifacts with the default naming convention (for easier integration with install scripts). This means that release artifacts will now be named slightly differently:
```diff
- keepalived-exporter-1.3.3.linux-amd64.tar.gz
+ keepalived-exporter_1.3.3_linux_amd64.tar.gz
```
=> Update to goreleaser v2

internal/collector/collector.go
This pull request addresses an issue with exporting excluded VIPs in JSON format.
Currently, when using JSON output, the keepalived_vrrp_excluded_state metric is missing because the excluded_vips field is absent from the Keepalived JSON output.
This fix ensures that the key, named evips, is correctly included in the JSON output, allowing the metric to be properly exported.
=> fix: export Excluded VIPs (evips) with JSON output"

.goreleaser.yaml
name_template is renamed to version_template:
https://goreleaser.com/deprecations/#snapshotname_template
=> build: fix deprecated snapshot property for goreleaser

.goreleaser.yaml
Closes: https://github.com/mehdy/keepalived-exporter/issues/196
=> build: support arm v6 and v7

.github/dependabot.yml, .goreleaser.yaml, deployments/release/Dockerfile
build docker images via Ko than the native goreleaser way so we can have an easier way to build multi-arch images.
Closes: #196
=> build: add kos integreation to goreleaser

.goreleaser.yaml
Set bare to true to omit any additional like md5 to the image name cf. https://ko.build/configuration/#naming-images
=> build: omit any additional to image name
