mehdy/keepalived-exporter

- internal/collector/collector.go
There were a bug on wrong value type for counter metrics like `keepalived_become_master` and others.
> Fix bug on wrong value type for counters

- README.md
- cmd/keepalived-exporter/main.go
- internal/collector/collector.go
Ping count config is available through `ping.count` arg.
> Make ping count configurable

- README.md
- cmd/keepalived-exporter/main.go
- go.mod
- go.sum
- internal/collector/collector.go
Replaced ping with check script for better customization on VIP health checking
Closes: #8
> Add check script

- Makefile
Creates needed release assets with Makefile
```
$ make release
```
> Create release assets with Makefile

- Makefile
- Fix bug on setting v in release filename
- Add release files to make clean
> Refactor Makefile release

- README.md
- internal/collector/collector.go
Also there were a bug for `keepalived_packet_len_err` metric that was exported as a Gauge Value
> Add _total postfix for counter metrics

- .github/semantic.yml
This will allow:
- allowMergeCommits
- allowRevertCommits
> ci: add config for semantic bot

- internal/collector/setter_test.go
Add tests for setter file in collector package
> test: add setter file tests

- README.md
- cmd/keepalived-exporter/main.go
registered at https://github.com/prometheus/prometheus/wiki/Default-port-allocations
> refactor: change default port to 9165

- internal/collector/collector.go
- internal/collector/parser.go
- internal/collector/parser_test.go
- internal/collector/setter.go
- internal/collector/setter_test.go
- test_files/keepalived.data
- test_files/keepalived.stats
Also fix bug on parsing vrrp data
> tests: add more parser tests

- internal/collector/collector.go
- internal/collector/collector_test.go
Also refactor `NewKeepalivedCollector`
> test: add collector tests

- internal/collector/collector.go
- internal/collector/parser.go
- internal/collector/parser_test.go
> fix: parse interface from virtual ip

- internal/collector/collector.go
Will log both stdout and stderr on check script failure
> feat: add stderr to check script error logging

- internal/collector/signal.go
- Add stderr on getting signum from keepalived
- Add stdout on unmarshaling failure
> refactor: add more detail to sigNum error logging

- Makefile
> build: remove v from version for make release command

- .github/semantic.yml
> ci: add semantic conf to check all commits as well

- internal/types/host/keepalived_host_collector_host.go
> fix: parse version from stderr in host mode

- internal/collector/collector.go
- internal/types/container/keepalived_container_collector_host.go
- internal/types/host/keepalived_host_collector_host.go
- internal/types/host/keepalived_host_collector_host_test.go
- internal/types/utils/vrrp.go
- internal/types/utils/vrrp_test.go
Keepalived VRRP script state introduced in v1.4.0 in this commit https://github.com/acassen/keepalived/commit/f4c8a8519cf11a453c30103f6f42c6e5e7a610c6
Closes: #57
> feat: don't warn if Keepalived doesn't support script state

- internal/types/utils/signals.go
- internal/types/utils/signals_test.go
- internal/types/utils/version.go
- internal/types/utils/version_test.go
It also contains some little code improvements
> test: add test for utils package

- Dockerfile
- README.md
Add Dockerfile and docs for Keepalived containerized deployment modes
> feat: add Dockerfile for Keepalived Exporter
